title: CUB RIS Lab
description: Wiki page for internal documentation
theme: just-the-docs
permalink: pretty

# Lab information
lab_name: CUB RIS Lab
lab_full_name: Constructor University Bremen - Robotics and Intelligent Systems Lab
team_leads:
  - name: Prof. Dr. Francesco Maurelli
    url: https://constructor.university/faculty-member/prof-dr-francesco-maurelli

# logo: "/assets/icons/cub-ris-logo-1.jpeg"
# favicon_ico: "/assets/icons/cub-ris-logo-1.jpeg"
url: https://cu-intelligentsystems.github.io
baseurl: /cub-cs-ris-lab

kramdown:
  toc_levels: 2..2

aux_links:
  Template Repository: https://github.com/CU-IntelligentSystems/cub-cs-ris-lab

# Color scheme supports "light" (default) and "dark"
color_scheme: light
