title: CUB RIS Lab
description: Wiki page for internal documentation
theme: just-the-docs
permalink: pretty

url: https://cu-intelligentsystems.github.io
baseurl: /cub-cs-ris-lab

aux_links:
  Template Repository: https://github.com/CU-IntelligentSystems/cub-cs-ris-lab

